import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#000000',
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingTop: Platform.OS === 'ios' ? 60 : 40,
        paddingBottom: 20,
        backgroundColor: '#000000',
    },
    backButton: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: 'rgba(255, 255, 255, 0.05)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    headerTitleContainer: {
        flex: 1,
        alignItems: 'center',
    },
    headerTitle: {
        fontSize: 17,
        fontWeight: '700',
        color: '#FFFFFF',
    },
    headerSubtitle: {
        fontSize: 11,
        fontWeight: '600',
        color: '#E8503A',
        textTransform: 'uppercase',
        letterSpacing: 1,
        marginBottom: 2,
    },
    saveAction: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: '#E8503A',
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#E8503A',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 4,
    },
    deleteAction: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: 'rgba(255, 68, 68, 0.1)',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 8,
    },
    headerActions: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    previewToggle: {
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 8,
        backgroundColor: 'rgba(255, 255, 255, 0.05)',
        marginRight: 12,
    },
    previewToggleText: {
        fontSize: 12,
        fontWeight: '700',
        color: '#E8503A',
        textTransform: 'uppercase',
    },
    scrollView: {
        flex: 1,
    },
    contentContainer: {
        paddingBottom: 100,
    },
    titleSection: {
        paddingHorizontal: 24,
        paddingVertical: 16,
    },
    titleInput: {
        fontSize: 34,
        fontWeight: '900',
        color: '#FFFFFF',
        letterSpacing: -1,
        marginBottom: 8,
    },
    dateText: {
        fontSize: 13,
        color: '#444444',
        fontWeight: '700',
        textTransform: 'uppercase',
    },
    toolbarContainer: {
        backgroundColor: '#0D0D0D',
        borderTopWidth: 1,
        borderBottomWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.05)',
        paddingVertical: 8,
    },
    categoryScroller: {
        marginBottom: 8,
    },
    categoryScrollerContent: {
        paddingHorizontal: 16,
    },
    toolbarDivider: {
        height: 1,
        backgroundColor: 'rgba(255, 255, 255, 0.05)',
        marginBottom: 8,
    },
    formatIconRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
        gap: 12,
    },
    formatIconGroup: {
        flexDirection: 'row',
        gap: 8,
        alignItems: 'center',
    },
    toolBtn: {
        width: 40,
        height: 40,
        borderRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',
    },
    toolBtnActive: {
        backgroundColor: 'rgba(232, 80, 58, 0.15)',
    },
    micBtn: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: '#161616',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.08)',
    },
    micBtnActive: {
        backgroundColor: 'rgba(255, 68, 68, 0.15)',
        borderColor: 'rgba(255, 68, 68, 0.4)',
    },
    micPulse: {
        position: 'absolute',
        width: 44,
        height: 44,
        borderRadius: 22,
        borderWidth: 2,
        borderColor: '#FF4444',
    },
    verticalDivider: {
        width: 1,
        height: 20,
        backgroundColor: 'rgba(255, 255, 255, 0.08)',
        marginHorizontal: 8,
    },
    categoryChip: {
        paddingHorizontal: 14,
        paddingVertical: 8,
        borderRadius: 12,
        backgroundColor: '#161616',
        marginRight: 8,
    },
    categoryChipActive: {
        backgroundColor: 'rgba(232, 80, 58, 0.1)',
        borderWidth: 1,
        borderColor: 'rgba(232, 80, 58, 0.3)',
    },
    categoryChipText: {
        fontSize: 13,
        fontWeight: '600',
        color: '#666666',
    },
    categoryChipTextActive: {
        color: '#E8503A',
        fontWeight: '700',
    },
    editorSection: {
        paddingHorizontal: 24,
        paddingTop: 20,
    },
    statusIndicator: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        backgroundColor: 'rgba(232, 80, 58, 0.05)',
        padding: 12,
        borderRadius: 12,
        marginBottom: 20,
    },
    statusText: {
        fontSize: 13,
        color: '#E8503A',
        fontWeight: '700',
    },
    recordingPulse: {
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: '#FF4444',
    },
    contentInput: {
        fontSize: 19,
        color: '#E0E0E0',
        lineHeight: 32,
        minHeight: 500,
    },
    interimOverlay: {
        position: 'absolute',
        bottom: 20,
        left: 0,
        right: 0,
        backgroundColor: 'rgba(232, 80, 58, 0.9)',
        padding: 10,
        borderRadius: 8,
        marginHorizontal: 24,
    },
    interimOverlayText: {
        color: '#FFF',
        fontSize: 14,
        fontWeight: '600',
        fontStyle: 'italic',
    },
    placeholderText: {
        fontSize: 19,
        color: 'rgba(255, 255, 255, 0.1)',
        lineHeight: 32,
        fontStyle: 'italic',
    },
    interimPreviewText: {
        fontSize: 19,
        color: 'rgba(255, 255, 255, 0.4)',
        lineHeight: 32,
        fontStyle: 'italic',
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.4)',
        justifyContent: 'flex-end',
        paddingBottom: 100,
        alignItems: 'center',
    },
    formatMenu: {
        width: '85%',
        backgroundColor: '#1A1A1A',
        borderRadius: 20,
        padding: 16,
    },
    menuHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 12,
    },
    headerTool: {
        width: 44,
        height: 44,
        borderRadius: 12,
        backgroundColor: '#262626',
        justifyContent: 'center',
        alignItems: 'center',
    },
    menuDivider: {
        height: 1,
        backgroundColor: 'rgba(255,255,255,0.05)',
        marginVertical: 4,
    },
    menuItem: {
        paddingVertical: 14,
    },
    menuItemTitle: { fontSize: 28, fontWeight: '900', color: '#FFF' },
    menuItemHeading: { fontSize: 22, fontWeight: '800', color: '#FFF' },
    menuItemSubheading: { fontSize: 18, fontWeight: '700', color: '#FFF' },
    menuItemBody: { fontSize: 18, color: '#FFF' },
    menuItemText: { fontSize: 18, color: '#FFF' },
    previewContainer: {
        flex: 1,
    },
    previewTitle: {
        fontSize: 32,
        fontWeight: '900',
        color: '#FFFFFF',
        marginBottom: 16,
    },
    previewHeading: {
        fontSize: 24,
        fontWeight: '800',
        color: '#FFFFFF',
        marginBottom: 12,
        marginTop: 16,
    },
    previewSubheading: {
        fontSize: 20,
        fontWeight: '700',
        color: '#FFFFFF',
        marginBottom: 10,
        marginTop: 14,
    },
    previewBody: {
        fontSize: 18,
        lineHeight: 28,
        color: '#E0E0E0',
        marginBottom: 12,
    },
    previewListItem: {
        fontSize: 18,
        lineHeight: 28,
        color: '#E0E0E0',
        marginBottom: 8,
        paddingLeft: 10,
    },
    previewQuote: {
        borderLeftWidth: 4,
        borderLeftColor: '#E8503A',
        paddingLeft: 16,
        marginVertical: 16,
        backgroundColor: 'rgba(232, 80, 58, 0.05)',
        paddingVertical: 12,
        borderRadius: 4,
    },
    previewQuoteText: {
        fontSize: 18,
        fontStyle: 'italic',
        lineHeight: 28,
        color: '#E0E0E0',
    },
});
